# -*- coding: utf-8 -*-
"""kaggle_colab_setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O9pEFgzejk54G4OZcgWRk3y436CETMrC
"""

# Utility File to Load Data for Coursera Kaggle Competition, from "migai/Kag" repository

'''
This file is addressed / loaded / executed from GitHub by Colab with the following commands:
try:
    import google.colab
    IN_COLAB = True
except:
    IN_COLAB = False
if IN_COLAB:
    print("Downloading Colab files")
    ! shred -u kaggle_colab_setup.py  # removes any previously-existing versions of the setup file
    ! wget https://raw.githubusercontent.com/migai/Kag/master/kaggle_colab_setup.py -O kaggle_colab_setup.py
    import kaggle_colab_setup
    kaggle_colab_setup.load_data()
'''

# Pointer when calling this repository from Colab:
git_hub_url = "https://raw.githubusercontent.com/migai/"
repo_name = 'Kag/'
branch_name = 'master/'
base_url = git_hub_url + repo_name + branch_name
import os
import pandas as pd

def download_file(url, file_path):
  print(url, file_path)
  if os.path.exists(file_path):
    os.remove(file_path)
  template = "wget '{}' -O '{}'"
  os.system(template.format(url, file_path))


def github_into_colab_py(path):
  url = base_url + '{}'
  file_path = path.rsplit("/")[-1]
  download_file(url.format(path), file_path)
  return

def github_into_colab_pandas_df(path, df_name):
  url = base_url + '{}'
  file_path = path.rsplit("/")[-1]
  download_file(url.format(path), file_path)
  df_name = pd.read_csv(file_path)
  return df_name


def load_data():
  #github_into_colab_py("utils/kag_utils.py")

  data_files = ["readonly/final_project_data/items.csv",
                "readonly/final_project_data/item_categories.csv",
                "readonly/final_project_data/shops.csv",
                "readonly/final_project_data/sample_submission.csv.gz",
                "readonly/final_project_data/sales_train.csv.gz",
                "readonly/final_project_data/test.csv.gz"  ]

  # initialize Pandas DataFrames to hold data from csv file imports
  # then load data from the GitHub repo into Google Colab dataframe
  for path_name in data_files:
    data_frame_name = path_name.rsplit("/")[-1].split(".")[0]
    exec(data_frame_name + " = pd.DataFrame()")
    github_into_colab_pandas_df(path_name,eval(data_frame_name))




'''
  items = pd.DataFrame()
  item_categories = pd.DataFrame()
  shops = pd.DataFrame()
  sample_submission = pd.DataFrame()
  sales_train = pd.DataFrame()
  test = pd.DataFrame()
  github_into_colab_pandas_df("readonly/final_project_data/items.csv", items)
  github_into_colab_pandas_df("readonly/final_project_data/item_categories.csv", item_categories)
  github_into_colab_pandas_df("readonly/final_project_data/shops.csv", shops)
  github_into_colab_pandas_df("readonly/final_project_data/sample_submission.csv.gz", sample_submission)
  github_into_colab_pandas_df("readonly/final_project_data/sales_train.csv.gz", sales_train)
  github_into_colab_pandas_df("readonly/final_project_data/test.csv.gz", sales_train)
'''

