# -*- coding: utf-8 -*-
"""kaggle_colab_setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/migai/Kag/blob/master/kaggle_colab_setup.ipynb
"""

# Utility File to Load Data for Coursera Kaggle Competition, from "migai/Kag" repository
import os
import pandas as pd

def download_file(url, file_path):
  print(url, file_path)
  if os.path.exists(file_path):
    os.remove(file_path)
  template = "wget '{}' -O '{}'"
  os.system(template.format(url, file_path))


def download_github_code(path):
  repo = 'Kag/blob'
  branch = 'master'
  url = 'https://github.com/migai/{}/{}/{}'
  file_path = path.rsplit("/")[-1]
  download_file(url.format(repo, branch, path), file_path)


def download_github_with_pd_csv(path, df_name):
  repo = 'Kag/blob'
  branch = 'master'
  url = 'https://github.com/migai/{}/{}/{}'
  file_path = path.rsplit("/")[-1]
  download_file(url.format(repo, branch, path), file_path)
  df_name = pd.read_csv(file_path)


def load_data():
  #download_github_code("utils/kag_utils.py")

  transactions = pd.DataFrame()
  items = pd.DataFrame()
  item_categories = pd.DataFrame()
  shops = pd.DataFrame()
  download_github_with_pd_csv("readonly/final_project_data/sales_train.csv.gz", transactions)
  download_github_with_pd_csv("readonly/final_project_data/items.csv", items)
  download_github_with_pd_csv("readonly/final_project_data/item_categories.csv", item_categories)
  download_github_with_pd_csv("readonly/final_project_data/shops.csv", shops)

